# NOTE: update this with your service name
service: serverless-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

# Optimization: See https://github.com/serverless-heaven/serverless-webpack#optimization--individual-packaging-per-function
package:
  individually: true

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getAccessToken:
    handler: index.getAccessToken
    events:
      - http:
          path: getAccessToken
          method: GET
          cors: true
    environment:
      SANDBOX_ATOM_CLIENT_ID: ${ssm:sandboxAtomClientId}
      SANDBOX_ATOM_CLIENT_SECRET: ${ssm:sandBoxAtomClientSecret}
  getRecommendedPortfolio:
    handler: index.getRecommendedPortfolio
    events:
      - http:
          path: getRecommendedPortfolio
          method: POST
          cors: true
